use std::ffi::{c_void, CStr};
use std::fmt;
use std::sync::Arc;

use eframe::glow;

use crate::video::pipewire::DmaBufFrame;

#[allow(dead_code)]
mod sys {
    // Constants generated by throw-away c script gen_egl_constants.c
    pub const WIDTH: i32 = 12375;
    pub const HEIGHT: i32 = 12374;
    pub const NONE: i32 = 12344;
    pub const LINUX_DMA_BUF_EXT: i32 = 12912;
    pub const LINUX_DRM_FOURCC_EXT: i32 = 12913;
    pub const DMA_BUF_PLANE0_FD_EXT: i32 = 12914;
    pub const DMA_BUF_PLANE0_OFFSET_EXT: i32 = 12915;
    pub const DMA_BUF_PLANE0_PITCH_EXT: i32 = 12916;
    pub const DMA_BUF_PLANE0_MODIFIER_LO_EXT: i32 = 13379;
    pub const DMA_BUF_PLANE0_MODIFIER_HI_EXT: i32 = 13380;
    pub const DRM_FORMAT_XRGB8888: u32 = 875713112;
    pub const DRM_FORMAT_MOD_LINEAR: u64 = 0;
}
pub use sys::DRM_FORMAT_XRGB8888;



// FFI function-pointer types

/// The proc-address resolver from eframe's `CreationContext`.
pub type GetProcAddr = Arc<dyn Fn(&CStr) -> *const c_void + Send + Sync>;

type PfnEglCreateImageKhr = unsafe extern "C" fn(
    dpy: *mut c_void,
    ctx: *mut c_void,
    target: u32,
    buffer: *mut c_void,
    attrib_list: *const i32,
) -> *mut c_void;

type PfnEglDestroyImageKhr = unsafe extern "C" fn(dpy: *mut c_void, image: *mut c_void) -> u32;

type PfnGlEglImageTargetTexture2dOes = unsafe extern "C" fn(target: u32, image: *mut c_void);

/// Errors from EGL construction or DMA-BUF import.
#[derive(Debug)]
pub enum EglError {
    MissingProc(&'static str),
    NoCurrentDisplay,
    CreateImage(Option<u32>),
}

impl fmt::Display for EglError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EglError::MissingProc(p) => write!(f, "missing proc: {p}"),
            EglError::NoCurrentDisplay => {
                write!(f, "no current EGLDisplay (GL context not current?)")
            }
            EglError::CreateImage(Some(code)) => {
                write!(f, "eglCreateImageKHR failed (error 0x{code:04x})")
            }
            EglError::CreateImage(None) => write!(f, "eglCreateImageKHR failed"),
        }
    }
}

impl std::error::Error for EglError {}

/// A live `EGLImageKHR`. Tied logically to the display it was created on.
pub struct EglImage(*mut c_void);
impl EglImage {
    pub fn as_ptr(&self) -> *mut c_void {self.0}
}

#[derive(Clone, Copy)]
pub struct EglDisplay(*mut c_void);
impl EglDisplay {
    pub fn as_ptr(&self) -> *mut c_void {self.0}
}

pub struct EglApi {
    pub gl_ctx: std::sync::Arc<glow::Context>,
    /// `eglGetCurrentDisplay`
    egl_get_current_display: unsafe extern "C" fn() -> *mut c_void,
    /// `eglGetError`
    egl_get_error: unsafe extern "C" fn() -> u32,
    /// `eglCreateImageKHR`
    create_image: PfnEglCreateImageKhr,
    /// `eglDestroyImageKHR`
    destroy_image: PfnEglDestroyImageKhr,
    /// `glEGLImageTargetTexture2DOES`
    image_target_texture_2d: PfnGlEglImageTargetTexture2dOes,
}

/// Resolve a symbol via the GL display's `get_proc_address`.
/// # Safety
/// The returned pointer must be cast to the target function type.
/// We use `transmute_copy` so the compiler doesn't try to verify size equality
/// between `*const c_void` and the fn type (they're always the same size).
unsafe fn resolve_fn<F>(get_proc_address: &GetProcAddr, name: &str) -> Option<F> {
    let cs = std::ffi::CString::new(name).ok()?;
    let ptr = get_proc_address(&cs);
    if ptr.is_null() {
        None
    } else {
        Some(unsafe { std::mem::transmute_copy(&ptr) })
    }
}

impl EglApi {
    pub fn new(gl_ctx: std::sync::Arc<glow::Context>, get_proc_address: &GetProcAddr) -> Result<Self, EglError> {
        let egl_get_current_display = unsafe {
            resolve_fn(get_proc_address, "eglGetCurrentDisplay")
                .ok_or_else(|| EglError::MissingProc("eglGetCurrentDisplay"))?
        };
        let egl_get_error = unsafe {
            resolve_fn(get_proc_address, "eglGetError")
                .ok_or_else(|| EglError::MissingProc("eglGetError"))?
        };
        let create_image = unsafe {
            resolve_fn(get_proc_address, "eglCreateImageKHR")
                .ok_or_else(|| EglError::MissingProc("eglCreateImageKHR"))?
        };
        let destroy_image = unsafe {
            resolve_fn(get_proc_address, "eglDestroyImageKHR")
                .ok_or_else(|| EglError::MissingProc("eglDestroyImageKHR"))?
        };
        let image_target_texture_2d = unsafe {
            resolve_fn(get_proc_address, "glEGLImageTargetTexture2DOES")
                .ok_or_else(|| EglError::MissingProc("glEGLImageTargetTexture2DOES"))?
        };

        Ok(EglApi {
            gl_ctx: gl_ctx.clone(),
            egl_get_current_display,
            egl_get_error,
            create_image,
            destroy_image,
            image_target_texture_2d,
        })
    }

    /// The `EGLDisplay` current on this thread.
    /// Must be called with the GL context current (from inside an egui paint callback).
    pub fn current_display(&self) -> Result<EglDisplay, EglError> {
        let dpy = unsafe { (self.egl_get_current_display)() };
        if dpy.is_null() {
            Err(EglError::NoCurrentDisplay)
        } else {
            Ok(EglDisplay(dpy))
        }
    }

    /// Import a single-plane DMA-BUF as an `EGLImageKHR`.
    pub fn create_dmabuf_image(
        &self,
        display: EglDisplay,
        frame: &DmaBufFrame,
    ) -> Result<EglImage, EglError> {
        let attribs: [i32; 13] = [
            sys::WIDTH,
            frame.width as i32,
            sys::HEIGHT,
            frame.height as i32,
            sys::LINUX_DRM_FOURCC_EXT,
            DRM_FORMAT_XRGB8888 as i32,
            sys::DMA_BUF_PLANE0_FD_EXT,
            frame.fd as i32,
            sys::DMA_BUF_PLANE0_OFFSET_EXT,
            frame.offset as i32,
            sys::DMA_BUF_PLANE0_PITCH_EXT,
            frame.stride,
            sys::NONE,
        ];

        // SAFETY: `display` is the current EGL display; ctx and buffer are null
        // as mandated for the LINUX_DMA_BUF target.
        let raw = unsafe {
            (self.create_image)(
                display.as_ptr(),
                std::ptr::null_mut(),
                sys::LINUX_DMA_BUF_EXT as u32,
                std::ptr::null_mut(),
                attribs.as_ptr(),
            )
        };

        if raw.is_null() {
            let code = unsafe { (self.egl_get_error)() };
            return Err(EglError::CreateImage(Some(code)));
        }

        Ok(EglImage(raw))
    }

    /// Bind `image` to the currently-bound texture on `target` (e.g. `glow::TEXTURE_2D`).
    ///
    /// # Safety
    /// A GL context must be current and a texture bound to `target`.
    pub unsafe fn bind_image_to_texture(&self, target: u32, image: &EglImage) {
        unsafe { (self.image_target_texture_2d)(target, image.as_ptr()) };
    }

    /// Destroy an image previously returned by [`Self::create_dmabuf_image`].
    pub fn destroy_image(&self, display: EglDisplay, image: EglImage) {
        unsafe { let _ = (self.destroy_image)(display.as_ptr(), image.as_ptr()); }
    }
}
