// // @generated by tools/gen_egl_constants.c from the system EGL/DRM headers. Do not edit by hand.
// // Regenerate: cc tools/gen_egl_constants.c -I/usr/include/drm -o gen_egl_constants && ./gen_egl_constants > src/egl_constants.rs

pub const WIDTH: i32 = 12375;
pub const HEIGHT: i32 = 12374;
pub const NONE: i32 = 12344;
pub const LINUX_DMA_BUF_EXT: i32 = 12912;
pub const LINUX_DRM_FOURCC_EXT: i32 = 12913;
pub const DMA_BUF_PLANE0_FD_EXT: i32 = 12914;
pub const DMA_BUF_PLANE0_OFFSET_EXT: i32 = 12915;
pub const DMA_BUF_PLANE0_PITCH_EXT: i32 = 12916;
pub const DMA_BUF_PLANE0_MODIFIER_LO_EXT: i32 = 13379;
pub const DMA_BUF_PLANE0_MODIFIER_HI_EXT: i32 = 13380;
pub const DRM_FORMAT_XRGB8888: u32 = 875713112;
pub const DRM_FORMAT_MOD_LINEAR: u64 = 0;
